branches:
  only:
    - develop
    - master
language: objective-c
osx_image: xcode7.2
notifications:
  slack:
    rooms:
      secure: RttO1aBKAm9r6DYsJuSs9DtCcw3HlrT43rmWJmNCpFA0Lq5TuI/LugBtGgiIbK4W4E1qIB+ouQwffQET4B+dI32hFBzlZb9Q9mpLX0RYwPjFg3pheIH8pm+iOUBBH590qGSGLk+Mcybm88bCRpXTHW8l6o6a/lClsKscK4khLvTYrxcDFi4chAvmh4egrXPYK7T2FPd57JIsIGmCCBwYsMoxK1sFFI32EuRFW9tWD1skX0HkJhkk54e5GADiMkKDSlp+lAa+9c2LMjpGDDS5hx+ljPGeFisS39dYvtMh5gS1sYXMHtvcDERl7V9HyvLdlcF1aYzGFxRi6eMu5GxQT//e/P1+MJkxcYibxnehTUpLMYd8bsIU2Sqz+VLzxbqfQUzliRAvEQ0J/SQlw3L52MJqbGk0GnRO7ZkarHj2j3AtfMIUi+U4FGJXZ4HZ8PG9IZTNBFoE8F2+f8PaPDrdtr6LG330rEJtK3bMqb6AsCASEe7ukfclOUKZSERAwzYDVFet1LvVkQoYdnxwfwk6qbonnrXtB0s1Dd9QAQonuxI7DcHGti6/Rsjk1xCAL78KmGXLTaPDBHRKiMtCIsnj1IS8ruuDl84AXn9vlTVzzYms2asCqCchvdc0cx4FboquLpxfm9INjPB+3DrYYCQdhAqI/9hrN82kmMxWNwm4XlQ=
    on_pull_requests: false
    on_failure: always
    on_start: never
    on_success: change
before_install:
  - rvm use $RVM_RUBY_VERSION
  - gem install cocoapods
  - pod install
script:
  - set -o pipefail && xcodebuild clean test -workspace SettingsKit.xcworkspace -scheme SettingsKit -destination 'platform=iOS Simulator,name=iPhone 6s' ONLY_ACTIVE_ARCH=YES | xcpretty
  - pod lib lint
